Docker: 'true'
resizeFactor: 1
preMask: 'true'
useGPUArray: 'false'
NucMaskChan: 1
ClassProbSource: 'unet'
inferNucCenters: 'true'
segmentNucleus: 'true'
logSigma: 2.5
nucleiRegion: 'watershedContourInt'
upSample: 2
CytoMaskChan: 2
TissueMaskChan: 3
segmentCytoplasm: 'segmentCytoplasm'
cytoMethod: 'distanceTransform'
nucleiPriority: 'false'
measureFeatures: 'false'
MedianIntensity: 'false'
saveFig: 'true'
saveMasks: 'true'
